spring.datasource.url: jdbc:h2:file:./accounts_db;DB_CLOSE_DELAY=-1
spring.datasource.username: sa
spring.datasource.password: sa
server.port: 8082
spring.h2.console.enabled: true
springdoc.show-actuator: true

com.devsu.services:
  clients:
    base-url: "http://localhost:8081/v1/clients"

