spring.datasource.url: jdbc:h2:mem:clients_db;DB_CLOSE_DELAY=-1
spring.datasource.username: sa
spring.datasource.password: sa
server.port: 8081
spring.jpa.generate-ddl: true
spring.h2.console.enabled: true
springdoc.show-actuator: true
spring:
  security:
    user:
      name: user
      password: pass
